#-----------------------------------------------------------------------------------------------------------------------
# Profile
#-----------------------------------------------------------------------------------------------------------------------
spring:
  profiles:
    active: dev
#-----------------------------------------------------------------------------------------------------------------------
# RGC budgeting general settings
#-----------------------------------------------------------------------------------------------------------------------
rgc:
  artifactId: "documentflow-admin"
#-----------------------------------------------------------------------------------------------------------------------
#internationalization
#-----------------------------------------------------------------------------------------------------------------------
  default:
    locale: uk_Ua
    encoding: UTF-8
