#-----------------------------------------------------------------------------------------------------------------------
# Profile
#-----------------------------------------------------------------------------------------------------------------------
spring:
  profiles:
    active: dev
#-----------------------------------------------------------------------------------------------------------------------
# RGC budgeting general settings
#-----------------------------------------------------------------------------------------------------------------------
rgc:
  artifactId: "@project.artifactId@"
  #-----------------------------------------------------------------------------------------------------------------------
  #internationalization
  #-----------------------------------------------------------------------------------------------------------------------
  default:
    locale: uk_Ua
    encoding: UTF-8
lombok:
  addLombokGeneratedAnnotation: true
